export const dummyData = {
    id: 1,
    searchTitle: "gia-dinh-bao-to",
    releaseYear: 2025,
    voteAverage: 8.667,
    metadataId: 101,
    numberOfEpisodes: 12,
    categories: ["Comedy", "Drama"],
    metadata: {
        id: 101,
        movieId: 1,
        title: "Shin's Project",
        originalTitle: "신사장 프로젝트",
        description:
            "A comic drama that tells the story of CEO Shin, who mediates disputes for people who are on the edge of a cliff with a 0% chance of winning.",
        numberOfEpisodes: 12,
        voteAverage: 8.667,
        voteCount: 3,
        popularity: 11.1131,
        posterPath: "https://image.tmdb.org/t/p/w300/iiBkY6mrYWdyosaHtJQm0pFXyBt.jpg",
        backdropPath: "https://image.tmdb.org/t/p/w1920/m0hmWbxQJPtHKQzSez55VnQE8YU.jpg",
        releaseDate: "2025-09-15",
        country: "KR",
        originalLanguage: "ko",
        genre: ["Comedy", "Drama"],
        actors: [
            { id: 1, name: "Han Suk-kyu", profilePath: "/AiGNpL7wZViKY0Lpvb03DNstY5b.jpg" },
            { id: 2, name: "Bae Hyeon-seong", profilePath: "/dUsVNDkAMAQP9fENDLNeaYXc8KB.jpg" },
            { id: 3, name: "Lee Re", profilePath: "/i1A5E4v5xRFammipC3H4jeOwczv.jpg" },
            { id: 4, name: "Kim Seung-o", profilePath: "/bvwsF0l3f2qs19GCUyHtAqGDL5P.jpg" },
            { id: 5, name: "Woo Mi-hwa", profilePath: "/vdQM14Su0CKBGiqvCs1X7rHhyei.jpg" },
        ],
        status: "Ended",
    },
}
